### PR TITLE
Lightline support

### PR DESCRIPTION
**Pull request by cultab**
Added lightline support.

By default the color setup is as similar to the screenshots as I could get.

If however a user adds the following to their config, the color setup is similar to what other lightline colorschemes do, eg: normal.left and normal.right match colors.
`let g:lightline#colorscheme#github_light#faithful = 0`

On the left is the faithful version, on the right the more traditional version
2020-06-01-170226_1599x696_scrot

### CODE REVIEW

**Comment by romgrk** [comment]
Cool :) A few questions:
 - If the user `colorscheme github-light`, will it auto-adjust the lightline colorscheme? If not, is there a way to make it?
 - Can you add documentation at the end of the readme on how to set it up for lightline users?

**Comment by cultab** [comment]
> Cool :) A few questions:
> 
> * If the user `colorscheme github-light`, will it auto-adjust the lightline colorscheme? If not, is there a way to make it?

Maybe, I'll try to see what I can do but I think you're not supposed to set it for the user (based on other colorschemes I've used) but I also can't see why not.
> * Can you add documentation at the end of the readme on how to set it up for lightline users?

Yes

**Comment by cultab** [comment]
I forgot to explain exactly what I did so:

I added some documentation and screenshots (obviously) but I could't get the lightline theme to work by just setting the colorscheme, it has to be done separately (I feel it's better this way).

**Comment by romgrk** [comment]
LGTM, thanks for the contribution :)

**Pull request merged**
